{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "resin-portal.secretName" . }}
  labels:
    {{- include "resin-portal.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ include "resin-portal.databaseURL" . | quote }}
  SESSION_SECRET: {{ .Values.app.sessionSecret | default (randAlphaNum 48) | quote }}
  ADMIN_PASSWORD: {{ .Values.app.adminPassword | quote }}
  STATUS_API_KEY: {{ .Values.app.statusApiKey | quote }}
  ENROLL_TOKEN: {{ .Values.app.enrollToken | quote }}
{{- end }}
